# ===========================================================
# MKID Durham Group — Official Website Configuration
# Based on "Beautiful Jekyll" (Dean Attali)
# ===========================================================

# --- Required options --- #

title: "MKID Durham Group"
author: "Microwave Kinetic Inductance Detector Research, Durham University"

# --- Navigation Bar Links --- #

navbar-links:
  Research:
    - Overview: "research/overview"
    - KIDSpec Project: "research/kidspec"
    - Detector Development: "research/detectors"
    - Optical Design: "research/optics"
    - Cryogenic Systems: "research/cryogenics"
  Members:
    - Group Members: "members/current"
    - Collaborators: "members/collaborators"
  Publications: "publications/"
  Outreach: "outreach/"
  Contact: "contact/"

# --- Logo and Branding --- #

title-img: "/assets/img/mkid_logo.png"
#round-avatar: true

# --- Footer Social Media Links --- #

social-network-links:
  email: "mkidgroup@durham.ac.uk"
  github: "Durham-MKID"
  youtube: /channel/UCb9MOi4lcNntMLo15oG8Z7A
  google-scholar: citations?user=iHJKYjIAAAAJ&hl=en
  orcid: "0000-0002-XXXX-XXXX"

rss-description: RSS feed for MKID Durham Group

# --- General Options --- #

share-links-active:
  twitter: true
  facebook: false
  linkedin: true

url-pretty: "mkid-durham.org"

excerpt_length: 50
feed_show_excerpt: true
feed_show_tags: false
post_search: true

keywords: "MKID, spectroscopy, Durham, CfAI, detector, KIDSpec, superconducting, time-domain, astronomy"

# --- Colours / Visual Design --- #

navbar-col: "#F3F4F6"
navbar-text-col: "#222222"
navbar-border-col: "#DDDDDD"
page-col: "#FFFFFF"
text-col: "#2E2E2E"
link-col: "#00539C"
hover-col: "#00467A"
footer-col: "#F3F4F6"
footer-text-col: "#666666"
footer-link-col: "#222222"
footer-hover-col: "#00539C"

# Optional background images
#navbar-img: "/assets/img/bg_dark.jpg"
#footer-img: "/assets/img/bg_dark.jpg"

mobile-theme-col: "#00539C"

# Optional custom CSS/JS
#site-css:
#  - "/assets/css/custom-styles.css"
#site-js:
#  - "/assets/js/custom.js"

# --- Web Analytics --- #
#gtag: ""
#google_analytics: ""
#cloudflare_analytics: ""

# --- Comments (optional) --- #
#disqus: ""
#commentbox: ""

# --- Misc --- #
date_format: "%B %-d, %Y"
timezone: "Europe/London"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# --- Default Page Settings --- #
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false
      social-share: true
  - scope:
      path: ""
    values:
      layout: "page"

# --- Files to Exclude --- #
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
